- name: show templating results
  debug:
    msg: "{{ lookup('template', 'some_template.j2') }}"

#- name: show templating results with different variable start and end string
#  debug:
#    msg: "{{ lookup('template', './some_template.j2', variable_start_string='[%', variable_end_string='%]') }}"
