---
- name: create a password and save to file
  debug: msg="{{ lookup('password', 'deploy-password.txt') }}"

- name: create a random password only
  debug: msg="{{ lookup('password', '/dev/null') }}"
