---
- name: filter surround_by_quote
  vars:
    domains:
      - "world"
      - "hello"
  debug: msg="{{ domains | surround_by_quote }}"



- name: filter surround_by_quote with loop
  vars:
    domains:
      - "world"
      - "hello"
  debug: msg="{{ item }}"
  loop: "{{ domains | surround_by_quote }}"
