---
- name: task in do.yml
  debug: msg="This task is in do.yml"

- name: create a file 
  copy: src=../files/sth.txt dest=/root/
  notify: when
  become: True

- name: Remove file (delete file)
  file:
    path: "{{ item }}"
    state: absent

  with_items:
    - /root/sth.txt
  notify: who
